### ISSUE TITLE
Rename public repository `Open-SymuVia` → `symuflow`

### ISSUE THREAD

**Issue by aladinoster** [licit-lab/Open-SymuVia#34]
Currently the repository is named [licit-lab/Open-SymuVia](https://github.com/licit-lab/Open-SymuVia). 

According to the naming policy licit-lab/symuflow-dev#7

Github redirects the old repository name toward the new one. https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

Example: I've renamed the code for `licit-lab/vanishing-control` → `licit-lab/enforcing-routing-dam`

**Comment by floriangc** [comment]
This repository is not supposed to be a sort of archive of the old code ?

**Comment by floriangc** [comment]
We discussed with @becarie and the conclusion is to make a clone of `symuflow-dev` and rename it `symuflow`.
We keep `Open-SymuVia` as it is for archive.

**Comment by aladinoster** [comment]
Ok, I'll:

- [x] copy the full repository `symuflow-dev` into `symuflow` and push content to the new public repository  
- [x] archive `Open-SymuVia`

Once done I'll close this issue
